import React from 'react'
import styles from './page.module.css'
import Image from 'next/image'
import Button from '@/components/button/Button'

export const metadata = {
  title: 'WizzyWay Contact',
  description: 'Generated by create next app',
}


const Contact = () => {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Let's keep in Touch : &apos; </h1>
      <div className={styles.content}>
        <div className={styles.imgContainer}>
          <Image 
          src="/contacted-transformed.png"
          alt=''
          fill={true} className={styles.img}
          />
        </div>
        <form className={styles.form}>
          <input type="text" placeholder='name' className={styles.input} />
          <input type="email" placeholder='email' className={styles.input} />
           <textarea className={styles.textArea} placeholder='message' cols="30" rows="10"></textarea>
           <Button url="#" text='Send' />
        </form>
      </div>
    </div>
  )
}

export default Contact